### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by lordrak007** [zdar/elan2mqtt#1]
Hi, i want test your gateway but after i win battle conetion to MGTT on hass.io, i am now getting this. It looks some failed when trying connect to eLan3.
Thanks

[2019-11-15 22:12:42,943] {main.py:191} INFO - Connected to MQTT broker
[2019-11-15 22:12:42,946] {main.py:203} INFO - Are we already authenticated? E.g. API check
[2019-11-15 22:12:42,957] {client.py:440} DEBUG - Watch broker disconnection
[2019-11-15 22:12:42,962] {main.py:370} ERROR - Something went wrong. But don't worry we will start over again.
[2019-11-15 22:12:42,962] {main.py:372} ERROR - But at first take some break. Sleeping for 30 s

Edit:
On LAN there are not any tries communicate to eLan to your GW must failt before it tries to connect.

**Comment by zdar** [comment]
Hi,
please try current version which improves compatibility with current eLan firmare.

  Jiri

**Comment by lordrak007** [comment]
Great. As i can see you done many changes. Good work and thank you.

**Comment by lordrak007** [comment]
Collecting yarl<2.0,>=1.0 (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/fb/84/6d82f6be218c50b547aa29d0315e430cf8a23c52064c92d0a8377d7b7357/yarl-1.3.0.tar.gz (159kB)
Collecting transitions (from hbmqtt->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ca/83/e579cc08917978421acd3418ab8f7d4ff68ade09ba51f41fb0499f075de3/transitions-0.7.1-py2.py3-none-any.whl (55kB)
Collecting websockets (from hbmqtt->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/e9/2b/cf738670bb96eb25cb2caf5294e38a9dc3891a6bcd8e3a51770dbc517c65/websockets-8.1.tar.gz (58kB)
Collecting passlib (from hbmqtt->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/11/b8/e9a78f3033228013ba8564adad8d0031bf9d39ea3acc3cdb9d55fabeb4ba/passlib-1.7.2-py2.py3-none-any.whl (507kB)
Collecting docopt (from hbmqtt->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting pyyaml (from hbmqtt->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
Collecting idna>=2.0 (from yarl<2.0,>=1.0->-r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
Collecting six (from transitions->hbmqtt->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Installing collected packages: argparse, six, transitions, websockets, passlib, docopt, pyyaml, hbmqtt, attrs, chardet, multidict, async-timeout, idna, yarl
  Running setup.py install for websockets: started
    Running setup.py install for websockets: finished with status 'done'
  Running setup.py install for docopt: started
    Running setup.py install for docopt: finished with status 'done'
  Running setup.py install for pyyaml: started
    Running setup.py install for pyyaml: finished with status 'done'
  Running setup.py install for multidict: started
    Running setup.py install for multidict: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_01k6rwc/multidict/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_01k6rwc/multidict/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-td__zjxj/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-_01k6rwc/multidict/
    Complete output (49 lines):
    **********************
    * Accellerated build *
    **********************
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/multidict
    copying multidict/_compat.py -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_abc.py -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict_base.py -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict_py.py -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/__init__.py -> build/lib.linux-x86_64-3.7/multidict
    running egg_info
    writing multidict.egg-info/PKG-INFO
    writing dependency_links to multidict.egg-info/dependency_links.txt
    writing top-level names to multidict.egg-info/top_level.txt
    reading manifest file 'multidict.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files found matching 'multidict/_multidict.html'
    warning: no previously-included files found matching 'multidict/*.so'
    warning: no previously-included files found matching 'multidict/*.pyd'
    warning: no previously-included files found matching 'multidict/*.pyd'
    no previously-included directories found matching 'docs/_build'
    writing manifest file 'multidict.egg-info/SOURCES.txt'
    copying multidict/__init__.pyi -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_istr.c -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_istr.h -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict.c -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict.pyx -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict_iter.c -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict_iter.h -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict_iter.pxd -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict_views.c -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict_views.h -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_multidict_views.pxd -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_pair_list.c -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_pair_list.h -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/_pair_list.pxd -> build/lib.linux-x86_64-3.7/multidict
    copying multidict/py.typed -> build/lib.linux-x86_64-3.7/multidict
    running build_ext
    building 'multidict._multidict' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/multidict
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.7m -c multidict/_multidict.c -o build/temp.linux-x86_64-3.7/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_01k6rwc/multidict/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_01k6rwc/multidict/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-td__zjxj/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by zdar** [comment]
Problem of imported library. Update requiremes.txt as is in repo now

**Comment by lordrak007** [comment]
Re: [zdar/elan2mqtt] Something went wrong (#1)



Hi, after few new update all workd very well. Good job.
Thank you

 





Problem of imported library. Update requiremes.txt as is in repo now
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.





--
S pozdravem,
 Lordrak
 mailto:lordrak007@seznam.cz
