### ISSUE TITLE
Not workign on Haas 2022.6 and newer - solved

### ISSUE THREAD

**Issue by lordrak007** [zdar/elan2mqtt#6]
Hi aftre long time.
aftre upgrade Haas to newestversion, your plugin stopped working. (I have no idey why it works until now, because i may wont)
This error occured in logs when i tried start plugin:  s6-overlay-suexec: fatal: can only run as pid 1

This can be solver by update config.json in your plugin
add this
"init": "false",

and remove this (not nescesarry but it is obsolote)
"startup": "before",

Thank you
Marek

PS: final config.json may be like this
{
  "init": "false",
  "name": "eLAN MQTT",
  "version": "1.16",
  "slug": "elan2mqtt",
  "description": "MQTT gateway for eLAN",
  "arch": ["armhf", "armv7", "aarch64", "amd64", "i386"],
  "boot": "auto",
  "options": {
    "eLanURL": "http://ip.address",
    "MQTTserver": "mqtt://username:password@ip.address",
    "username": "admin",
    "password": "elkoep",
    "log_level": "notice",
    "disable_autodiscovery": "false",
    "mqtt_id": ""
  },
  "schema": {
    "eLanURL": "str",
    "MQTTserver": "str",
    "username": "str",
    "password": "str",
    "log_level": "match(^(trace|debug|info|notice|warning|error|fatal)$)",
    "disable_autodiscovery": "bool?",
    "mqtt_id": "str?"
  },
  "environment": {
    "LOG_FORMAT": "{LEVEL}: {MESSAGE}"
  }
}

**Comment by zdar** [comment]
Thanks. Config updated.
